import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import {ReactNode} from 'react';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: { children: ReactNode }) {
  return (
    <html lang="en">
    <body className="p-6">
    <nav className="mb-6 space-x-4 border-b pb-2">
      <Link href="/upload">Upload</Link>
      <Link href="/tracks">Tracks</Link>
      <Link href="/albums">Albums</Link>
    </nav>
    {children}
    </body>
    </html>
  );
}
